services:
  - type: web
    name: pdf-to-excel-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
      - import os
openai.api_key = os.getenv("OPENAI_API_KEY")
